export type WithdrawalStatus = "prepared"|"burn_signed"|"gateway_submitted"|"attestation_received"|"mint_submission_pending"|"mint_submitted"|"finalized"|"failed"|"expired"|"reconciliation_required";
export type DepositStatus = "prepared"|"approval_submitted"|"approval_confirmed"|"deposit_submitted"|"finalized"|"failed"|"reconciliation_required";
export type Hex = `0x${string}`;
export interface Owner { id:string }
export interface StoredWallet { ownerId:string; walletId:string; address:string; blockchain:string; status:"active"|"pending" }
export interface BurnIntent { maxBlockHeight:string; maxFee:string; spec:TransferSpec }
export interface TransferSpec { version:number; sourceDomain:number; destinationDomain:number; sourceContract:string; destinationContract:string; sourceToken:string; destinationToken:string; sourceDepositor:string; destinationRecipient:string; sourceSigner:string; destinationCaller:string; value:string; salt:string; hookData:string }
export interface WithdrawalRecord { id:string; ownerId:string; walletId:string; walletAddress:string; amountAtomic:string; idempotencyKey:string; status:WithdrawalStatus; burnIntent:BurnIntent; burnIntentDigest:string; transferId:string|null; attestationHash:string|null; mintIdempotencyKey:string|null; circleTransactionId:string|null; txHash:string|null; errorCode:string|null; errorMessage:string|null; createdAt:string; updatedAt:string }
export interface CreateWithdrawalInput { ownerId:string; wallet:StoredWallet; amountAtomic:string; idempotencyKey:string; burnIntent:BurnIntent; burnIntentDigest:string }
export interface DepositRecord { id:string; ownerId:string; walletId:string; walletAddress:string; amountAtomic:string; idempotencyKey:string; status:DepositStatus; approvalTransactionId:string|null; depositTransactionId:string|null; errorCode:string|null; errorMessage:string|null; createdAt:string; updatedAt:string }
export interface CreateDepositInput { ownerId:string; wallet:StoredWallet; amountAtomic:string; idempotencyKey:string }
export interface GatewayEstimate { burnIntent:BurnIntent; transferSpecHash?:string; feeAtomic?:string }
export interface GatewayTransfer { transferId:string; attestationPayload?:string; attestationSignature?:string; transactionHash?:string; status:string }
export interface GatewayBalance { availableAtomic:bigint; availableUsdc:string; pendingAtomic?:bigint; pendingUsdc?:string }
export type BalanceResult = {ok:true; balance:GatewayBalance}|{ok:false; errorCode:"unavailable"|"malformed"|"unauthorized"; error:string}
export interface GatewayClient { estimate(spec:TransferSpec):Promise<GatewayEstimate>; submit(intent:BurnIntent,signature:string):Promise<{transferId:string; attestationHash:string}>; getTransfer(transferId:string):Promise<GatewayTransfer>; getBalances(input:{depositor:string}):Promise<BalanceResult> }
export interface DcwWalletProvider { provisionWallet(ownerId:string):Promise<StoredWallet>; getOnchainUsdc(wallet:StoredWallet):Promise<{atomic:bigint;usdc:string}>; approveGateway(wallet:StoredWallet,amountAtomic:string,idempotencyKey:string):Promise<{transactionId:string}>; getTransaction(transactionId:string):Promise<{state:string;txHash?:string}>; depositGateway(wallet:StoredWallet,amountAtomic:string,idempotencyKey:string):Promise<{transactionId:string}>; signBurnIntent(wallet:StoredWallet,intent:BurnIntent):Promise<string>; mint(wallet:StoredWallet,payload:string,signature:string,idempotencyKey:string):Promise<{transactionId:string}> }
export interface IdentityProvider { getOwner():Promise<Owner> }
export interface WalletStore { findByOwner(ownerId:string):Promise<StoredWallet|null>; save(wallet:StoredWallet):Promise<void> }
export interface WithdrawalStore { findById(id:string):Promise<WithdrawalRecord|null>; findByIdempotencyKey(ownerId:string,key:string):Promise<WithdrawalRecord|null>; create(input:CreateWithdrawalInput):Promise<{created:boolean;record:WithdrawalRecord}>; compareAndSet(id:string,expected:WithdrawalStatus,next:WithdrawalStatus,patch?:Partial<WithdrawalRecord>):Promise<WithdrawalRecord|null>; update(id:string,patch:Partial<WithdrawalRecord>):Promise<WithdrawalRecord|null> }
export interface DepositStore { findById(id:string):Promise<DepositRecord|null>; findByIdempotencyKey(ownerId:string,key:string):Promise<DepositRecord|null>; create(input:CreateDepositInput):Promise<{created:boolean;record:DepositRecord}>; compareAndSet(id:string,expected:DepositStatus,next:DepositStatus,patch?:Partial<DepositRecord>):Promise<DepositRecord|null>; update(id:string,patch:Partial<DepositRecord>):Promise<DepositRecord|null> }
